### ISSUE TITLE
Not able to initiate the project

### ISSUE THREAD

**Issue by darshk07** [vratix-dev/api-library#18]
Tried the elevated powershell as well, but stiil showing the same message. 
The "mkdir" command works perfectly if executed explicitly.
System: Windows 11
![{B013BD1D-9CC7-44C0-8114-1DCEC1D99845}](https://github.com/user-attachments/assets/39d88186-943c-4a0e-9d09-a0b7151112ab)

**Comment by ivan-ivanovv** [comment]
Hey @darshk07 thanks for reporting this. Can you share the CLI version you are using? You can get that with `npx vratix -V`

I will look into it today and get a fix out asap.

**Comment by darshk07** [comment]
I'm trying to use the latest one only.
**v.1.0.7**

**Comment by ivan-ivanovv** [comment]
Hey @darshk07 I have resolved the issue, we will try to publish the fix tomorrow. I will update the issue once the new CLI is live

**Comment by ivan-ivanovv** [comment]
Hey @darshk07 we just released v1.0.8 of the CLI that fixes bugs on Windows. I tested this on a Windows VM so lmk if it works fine on your machine. I am closing this issue now, feel free to reopen it if you still experience issues on `init` or `add`.
